version: "3"

services:
   db:
     container_name: "${PROJECT_NAME}-mongodb"
     image: mongo:3.0.14
     volumes:
      - "${MONGODB_DATA_PATH}:/data/db"
     ports:
      - "27017"
     restart: always
   rabbit:
     image: rabbitmq:3.6.14
     container_name: "${PROJECT_NAME}-rabbit"
     ports:
      - "15672"
      - "5672"
     restart: always
   api:
     container_name: "${PROJECT_NAME}-api"
     build: ./src/api
     volumes:
      - "./src/api:/usr/src/app"
     ports:
      - "${API_HTTP_PORT}:3005"
     env_file: './src/api/.env' 
     environment:
      - PORT=3005
      - ELASTIC_HOST=${PROJECT_NAME}-elasticsearch
      - RABBITMQ_HOST=${PROJECT_NAME}-rabbit
      - DB_PORT_27017_TCP_ADDR=${PROJECT_NAME}-mongodb
     restart: always
   elasticsearch:
     container_name: "${PROJECT_NAME}-elasticsearch"
     image: elasticsearch:2.4.2
     ports:
       - "9200"
     volumes:
      - "${ELASTIC_DATA_PATH}:/usr/share/elasticsearch/data"
     restart: always
   app:
     container_name: "${PROJECT_NAME}-app"
     build: ./src/app
     volumes: 
      - "./src/app:/usr/src/app"
     ports:
      - "${APP_HTTP_PORT}:3000"
      - "3001:3001"
     environment:
      - API_URL=http://${PROJECT_NAME}-api:3005
     restart: always
     


